-- ===================================================
-- CERCLES — Topic Seed Data
-- Run after 001_schema.sql
-- ===================================================

insert into topics (text, category) values
-- FUN
('Pineapple belongs on pizza', 'fun'),
('Cats are better than dogs', 'fun'),
('Summer is better than winter', 'fun'),
('Morning people have better lives than night owls', 'fun'),
('Cereal before milk is the only correct way', 'fun'),
('A hot dog is a sandwich', 'fun'),
('GIFs should be pronounced "jif"', 'fun'),
('The best superpower is invisibility, not flying', 'fun'),
('Toilet paper should go over, not under', 'fun'),
('Monopoly ruins friendships more than it creates them', 'fun'),
('The movie is always better than the book', 'fun'),
('Dessert should come before dinner', 'fun'),
('Silence is better background noise than music while working', 'fun'),
('Theme parks are overrated', 'fun'),
('You should always eat the last slice without asking', 'fun'),

-- LIFESTYLE
('Remote work is better than office work', 'lifestyle'),
('Social media does more harm than good', 'lifestyle'),
('You should tell your friends uncomfortable truths', 'lifestyle'),
('A tidy home leads to a tidy mind', 'lifestyle'),
('Routines kill spontaneity', 'lifestyle'),
('It''s better to rent than to own', 'lifestyle'),
('You should keep your salary secret from friends', 'lifestyle'),
('Hustle culture is toxic', 'lifestyle'),
('Having fewer close friends is better than many casual ones', 'lifestyle'),
('Journaling is a waste of time', 'lifestyle'),
('Living in a big city is better than the countryside', 'lifestyle'),
('You should never lend money to friends', 'lifestyle'),
('Taking a gap year is a mistake', 'lifestyle'),
('People should work to live, not live to work', 'lifestyle'),
('Spending on experiences beats spending on things', 'lifestyle'),

-- RELATIONSHIPS
('Long-distance relationships never work', 'relationships'),
('You should share all your passwords with your partner', 'relationships'),
('Age gaps in relationships are always problematic', 'relationships'),
('Exes can''t be just friends', 'relationships'),
('You should marry your best friend', 'relationships'),
('Open relationships are just as valid as monogamy', 'relationships'),
('Couples who argue are healthier than couples who don''t', 'relationships'),
('You should never go to sleep angry', 'relationships'),
('Social media is the biggest threat to modern relationships', 'relationships'),
('Moving in together before marriage is essential', 'relationships'),
('Love at first sight is real', 'relationships'),
('Friendship is more important than romantic love', 'relationships'),
('It''s acceptable to snoop on your partner''s phone', 'relationships'),
('Children make a relationship stronger', 'relationships'),
('You can choose who you fall in love with', 'relationships'),

-- PHILOSOPHY
('Free will is an illusion', 'philosophy'),
('Morality is objective, not subjective', 'philosophy'),
('A fulfilling life requires suffering', 'philosophy'),
('The ends justify the means', 'philosophy'),
('Humans are fundamentally selfish', 'philosophy'),
('Ignorance is bliss', 'philosophy'),
('It''s better to be honest than kind', 'philosophy'),
('Life has inherent meaning', 'philosophy'),
('Progress is always good', 'philosophy'),
('Justice and fairness are the same thing', 'philosophy'),
('It''s possible to be truly selfless', 'philosophy'),
('Technology makes us less human', 'philosophy'),
('The present moment is all that matters', 'philosophy'),
('Society needs rules more than freedom', 'philosophy'),
('Failure is more valuable than success', 'philosophy'),

-- POLITICS
('Voting should be mandatory', 'politics'),
('Wealth taxes are fair', 'politics'),
('Open borders would benefit society', 'politics'),
('Social media should be regulated by governments', 'politics'),
('Universal basic income would work', 'politics'),
('Prisons should focus on rehabilitation, not punishment', 'politics'),
('The death penalty can ever be justified', 'politics'),
('Governments should control the price of essential goods', 'politics'),
('Democracy is the best form of government', 'politics'),
('Affirmative action is fair', 'politics'),
('Nuclear energy is essential for the future', 'politics'),
('Drugs should be decriminalized', 'politics'),
('Lobbying is legal corruption', 'politics'),
('Free speech has limits', 'politics'),
('Nations have a duty to accept refugees', 'politics'),

-- TECH
('AI will do more harm than good', 'tech'),
('Privacy is dead and we should accept it', 'tech'),
('Social media algorithms radicalize people', 'tech'),
('Everyone should learn to code', 'tech'),
('Cryptocurrency is a scam', 'tech'),
('Screen time limits for children are the parents'' job, not the state''s', 'tech'),
('The internet has made us dumber', 'tech'),
('Tech billionaires have too much power', 'tech'),
('Self-driving cars are safer than human drivers', 'tech'),
('Video games cause violence', 'tech'),
('Working in tech is overrated', 'tech'),
('The metaverse will replace real-world experiences', 'tech'),
('You should own your data', 'tech'),
('Automation will create more jobs than it destroys', 'tech'),
('Smartphones have made us less social', 'tech'),

-- HOT TAKES
('Nice guys finish last', 'hot_takes'),
('Nepotism is just networking', 'hot_takes'),
('Participation trophies are harmful', 'hot_takes'),
('Cancel culture has gone too far', 'hot_takes'),
('Beauty standards are always someone''s fault', 'hot_takes'),
('True crime content glamorizes violence', 'hot_takes'),
('Influencers are a legitimate career', 'hot_takes'),
('Tipping culture should be abolished', 'hot_takes'),
('Millennials had it easier than Gen Z', 'hot_takes'),
('Art has no value unless it makes money', 'hot_takes'),
('Professional sports are a waste of public money', 'hot_takes'),
('People who don''t vote have no right to complain', 'hot_takes'),
('Comfort zones should be broken regularly', 'hot_takes'),
('Fame is a curse more than a gift', 'hot_takes'),
('Traditional gender roles still serve a purpose', 'hot_takes'),

-- WOULD YOU RATHER
('Be rich and unknown vs famous and broke', 'would_you_rather'),
('Know when you''ll die vs know how you''ll die', 'would_you_rather'),
('Have no internet for a year vs no human contact for a month', 'would_you_rather'),
('Always say what you think vs never speak again', 'would_you_rather'),
('Live 200 years in mediocrity vs 40 years at your peak', 'would_you_rather'),
('Read minds vs see the future', 'would_you_rather'),
('Be the funniest person in the room vs the smartest', 'would_you_rather'),
('Lose all your memories vs never make new ones', 'would_you_rather'),
('Have one true love vs ten great friendships', 'would_you_rather'),
('Be always cold vs always hot', 'would_you_rather'),
('Work a job you hate for 10 years and retire vs enjoy work forever', 'would_you_rather'),
('Have perfect health vs perfect wealth', 'would_you_rather'),
('Always be 10 minutes late vs always be 1 hour early', 'would_you_rather'),
('Know every language vs play every instrument', 'would_you_rather'),
('Live in the past vs the future', 'would_you_rather');
